= Quick Start with Proteus Spring module


In this section we are going to learn how to bootstrap Proteus Spring Boot Application.

== Set up dependencies

As the first step of any applications setup is generating the base application. For
that purpose we may use http://start.spring.io[start.spring.io].

Once the base application is generated or there is an existing one, use the following
dependency on the Proteus Spring Boot Starter:

[subs=attributes+]
[source,groovy]
.build.gradle
----
dependencies {
   ...
   compile "io.netifi.proteus:proteus-spring-boot-starter:{appversion}"
}
----

The above code-snippet shows how we may bring required dependencies in to our Gradle
based Spring Boot Application.

In the case of the Maven build-tool, the dependency on the starter is the following:

[subs=attributes+]
[source,xml]
.pom.xml
----
<dependency>
    <groupId>io.netifi.proteus</groupId>
    <artifactId>proteus-spring-boot-starter</artifactId>
    <version>{appversion}</version>
</dependency>
----

== Set up required properties

Once the dependency is set up, we have to configure mandated properties in order to
access Proteus Broker. The following shows how we may do that in `application.properties`
file:

[source,properties]
.application.properties
----
netifi.proteus.broker.hostname=localhost // <1>
netifi.proteus.broker.port=8001 // <1>

netifi.proteus.access.key=9007199254740991 // <2>
netifi.proteus.access.token=kTBDVtfRBO4tHOnZzSyY5ym2kfY= // <2>

netifi.proteus.group=quickstart.clients // <3>
----
<1> This is configurations of the Proteus Broker host and port.
<2> This is configurations of access key and token
<3> This is a configuration of current application group name

The `application.properties` file above demonstrates a mandatory properties of every
Spring Boot application.

NOTE: Proteus Spring Boot Starter brings all required autoconfigurations, so the
above is a minimal set up in order to bring all required functionality into the
application


